# Grab the :latest official Apache image
FROM httpd

# Copy a custom Apache config file
# The file contains VirtualHost configs to use as a proxy pass
COPY httpd.conf /usr/local/apache2/conf/httpd.conf